name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11' # See https://hub.docker.com/_/postgres for available versions
        postgresql user: 'postgres'
        postgresql password: 'postgres'
    - name: Install dependencies
      run: bundle install
    - name: Prepare database
      run: bin/task_runner prepare_all
      env:
        EVENT_SOURCED_DOMAINS_DATABASE_URL: postgres://postgres:postgres@localhost/
    - name: Run tests
      run: bundle exec rspec
      env:
        EVENT_SOURCED_DOMAINS_DATABASE_URL: postgres://postgres:postgres@localhost/
